2016-06-25 23:02:46,863 INFO  File: Research.Api started
2016-06-25 23:02:47,085 INFO  File: API:Seeking methods in assembly mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:02:47,100 INFO  File: ~API:Seeking methods in assembly mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:02:47,102 INFO  File: API:Seeking methods in assembly System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:02:47,117 INFO  File: ~API:Seeking methods in assembly System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:02:47,119 INFO  File: API:Seeking methods in assembly System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:02:47,130 INFO  File: ~API:Seeking methods in assembly System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:02:47,132 INFO  File: API:Seeking methods in assembly System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:02:47,140 INFO  File: ~API:Seeking methods in assembly System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:02:47,142 INFO  File: API:Seeking methods in assembly System.Web.ApplicationServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:02:47,144 INFO  File: ~API:Seeking methods in assembly System.Web.ApplicationServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:02:47,146 INFO  File: API:Seeking methods in assembly System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:02:47,148 INFO  File: ~API:Seeking methods in assembly System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:02:47,150 INFO  File: API:Seeking methods in assembly System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:02:47,158 INFO  File: ~API:Seeking methods in assembly System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:02:47,160 INFO  File: API:Seeking methods in assembly System.Runtime.Caching, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:02:47,162 INFO  File: ~API:Seeking methods in assembly System.Runtime.Caching, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:02:47,164 INFO  File: API:Seeking methods in assembly Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:02:47,167 INFO  File: ~API:Seeking methods in assembly Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:02:47,169 INFO  File: API:Seeking methods in assembly Microsoft.JScript, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:02:47,172 INFO  File: ~API:Seeking methods in assembly Microsoft.JScript, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:02:47,174 INFO  File: API:Seeking methods in assembly Microsoft.VisualStudio.Web.PageInspector.Loader, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:02:47,176 INFO  File: ~API:Seeking methods in assembly Microsoft.VisualStudio.Web.PageInspector.Loader, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:02:47,178 INFO  File: API:Seeking methods in assembly Microsoft.VisualStudio.Web.PageInspector.Runtime, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:02:47,183 INFO  File: ~API:Seeking methods in assembly Microsoft.VisualStudio.Web.PageInspector.Runtime, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:02:47,185 INFO  File: API:Seeking methods in assembly App_global.asax.66muct9v, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:02:47,187 INFO  File: ~API:Seeking methods in assembly App_global.asax.66muct9v, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:02:47,189 INFO  File: API:Seeking methods in assembly Research.Web.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:02:47,191 INFO  File: API:Method added: Account.Login
2016-06-25 23:02:47,194 INFO  File: API:Method added: Account.Read
2016-06-25 23:02:47,196 INFO  File: API:Method added: Account.Registration
2016-06-25 23:02:47,199 INFO  File: API:Method added: Account.Logout
2016-06-25 23:02:47,201 INFO  File: API:Method added: Account.GetStudents
2016-06-25 23:02:47,203 INFO  File: API:Method added: Account.SetStudent
2016-06-25 23:02:47,205 INFO  File: API:Method added: Questions.Get
2016-06-25 23:02:47,207 INFO  File: API:Method added: Questions.GetTypes
2016-06-25 23:02:47,210 INFO  File: API:Method added: Questions.GetSubjects
2016-06-25 23:02:47,212 INFO  File: API:Method added: Questions.SetSubject
2016-06-25 23:02:47,214 INFO  File: API:Method added: Questions.GetQuestionByType
2016-06-25 23:02:47,216 INFO  File: API:Method added: Questions.GetNextQuestion
2016-06-25 23:02:47,219 INFO  File: API:Method added: Questions.GetAllForQuestions
2016-06-25 23:02:47,222 INFO  File: API:Method added: Questions.SetQuestion
2016-06-25 23:02:47,225 INFO  File: API:Method added: Questions.GetQuestions
2016-06-25 23:02:47,227 INFO  File: ~API:Seeking methods in assembly Research.Web.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:02:47,230 INFO  File: API:Seeking methods in assembly System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:02:47,238 INFO  File: ~API:Seeking methods in assembly System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:02:47,240 INFO  File: API:Seeking methods in assembly log4net, Version=1.2.13.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a
2016-06-25 23:02:47,246 INFO  File: ~API:Seeking methods in assembly log4net, Version=1.2.13.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a
2016-06-25 23:02:47,247 INFO  File: API:Seeking methods in assembly DevReactor.Toolbox.Tools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:02:47,250 INFO  File: ~API:Seeking methods in assembly DevReactor.Toolbox.Tools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:02:47,252 INFO  File: API:Seeking methods in assembly DevReactor.Toolbox.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:02:47,278 INFO  File: ~API:Seeking methods in assembly DevReactor.Toolbox.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:02:47,280 INFO  File: API:Seeking methods in assembly System.Web.Mobile, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:02:47,313 INFO  File: ~API:Seeking methods in assembly System.Web.Mobile, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:02:47,315 INFO  File: API:Seeking methods in assembly System.Web.RegularExpressions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:02:47,318 INFO  File: ~API:Seeking methods in assembly System.Web.RegularExpressions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:02:47,320 INFO  File: API:Seeking methods in assembly Microsoft.VisualStudio.Web.PageInspector.Tracing, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:02:47,323 INFO  File: ~API:Seeking methods in assembly Microsoft.VisualStudio.Web.PageInspector.Tracing, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:02:47,325 INFO  File: API:Seeking methods in assembly App_Web_wnfrcjdk, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:02:47,327 INFO  File: ~API:Seeking methods in assembly App_Web_wnfrcjdk, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:02:47,329 INFO  File: API:Seeking methods in assembly Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
2016-06-25 23:02:47,338 INFO  File: ~API:Seeking methods in assembly Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
2016-06-25 23:02:47,340 INFO  File: API:Seeking methods in assembly System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:02:47,342 INFO  File: ~API:Seeking methods in assembly System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:02:47,345 INFO  File: API:Seeking methods in assembly System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:02:47,349 INFO  File: ~API:Seeking methods in assembly System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:02:47,352 INFO  File: API:Seeking methods in assembly System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:02:47,354 INFO  File: ~API:Seeking methods in assembly System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:02:47,357 INFO  File: API:Seeking methods in assembly System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:02:47,366 INFO  File: ~API:Seeking methods in assembly System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:02:47,576 INFO  File: API:Seeking methods in assembly System.ServiceModel.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:02:47,579 INFO  File: ~API:Seeking methods in assembly System.ServiceModel.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:02:47,581 INFO  File: API:Seeking methods in assembly Research.Logic, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:02:47,584 INFO  File: ~API:Seeking methods in assembly Research.Logic, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:02:47,586 INFO  File: API:Seeking methods in assembly System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:02:47,589 INFO  File: ~API:Seeking methods in assembly System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:02:47,591 INFO  File: API:Seeking methods in assembly DevReactor.Toolbox.BO, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:02:47,595 INFO  File: ~API:Seeking methods in assembly DevReactor.Toolbox.BO, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:02:47,597 INFO  File: API:Seeking methods in assembly System.WorkflowServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:02:47,622 INFO  File: ~API:Seeking methods in assembly System.WorkflowServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:02:47,625 INFO  File: API:Seeking methods in assembly MaxMind.GeoIP2, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:02:47,627 INFO  File: ~API:Seeking methods in assembly MaxMind.GeoIP2, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:02:47,630 INFO  File: API:Seeking methods in assembly System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:02:47,634 INFO  File: ~API:Seeking methods in assembly System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:02:47,637 INFO  File: API:Seeking methods in assembly System.ServiceModel.Activation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:02:47,640 INFO  File: ~API:Seeking methods in assembly System.ServiceModel.Activation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:02:47,643 INFO  File: API:Seeking methods in assembly System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:02:47,665 INFO  File: ~API:Seeking methods in assembly System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:02:47,668 INFO  File: API:Seeking methods in assembly Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:02:47,672 INFO  File: ~API:Seeking methods in assembly Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:02:47,674 INFO  File: API:Seeking methods in assembly System.ServiceModel.Activities, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:02:47,678 INFO  File: ~API:Seeking methods in assembly System.ServiceModel.Activities, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:02:47,681 INFO  File: API:Seeking methods in assembly MaxMind.Db, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:02:47,684 INFO  File: ~API:Seeking methods in assembly MaxMind.Db, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:02:47,687 INFO  File: API:Seeking methods in assembly System.Data.DataSetExtensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:02:47,691 INFO  File: ~API:Seeking methods in assembly System.Data.DataSetExtensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:02:47,693 INFO  File: API:Seeking methods in assembly Oracle.ManagedDataAccess, Version=4.121.1.0, Culture=neutral, PublicKeyToken=89b483f429c47342
2016-06-25 23:02:47,715 INFO  File: ~API:Seeking methods in assembly Oracle.ManagedDataAccess, Version=4.121.1.0, Culture=neutral, PublicKeyToken=89b483f429c47342
2016-06-25 23:02:47,718 INFO  File: API:Seeking methods in assembly System.Web.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:02:47,722 INFO  File: ~API:Seeking methods in assembly System.Web.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:02:47,725 INFO  File: API:Seeking methods in assembly DevReactor.Toolbox.Encrypting, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:02:47,727 INFO  File: ~API:Seeking methods in assembly DevReactor.Toolbox.Encrypting, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:02:47,729 INFO  File: API:Seeking methods in assembly System.Web.DynamicData, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:02:47,737 INFO  File: ~API:Seeking methods in assembly System.Web.DynamicData, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:02:47,739 INFO  File: API:Seeking methods in assembly System.ComponentModel.DataAnnotations, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:02:47,741 INFO  File: ~API:Seeking methods in assembly System.ComponentModel.DataAnnotations, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:02:47,743 INFO  File: API:Seeking methods in assembly RestSharp, Version=105.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:02:47,750 INFO  File: ~API:Seeking methods in assembly RestSharp, Version=105.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:02:47,752 INFO  File: API:Seeking methods in assembly Research.BO, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:02:47,755 INFO  File: ~API:Seeking methods in assembly Research.BO, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:02:47,757 INFO  File: API:Seeking methods in assembly System.EnterpriseServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:02:47,764 INFO  File: ~API:Seeking methods in assembly System.EnterpriseServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:02:47,767 INFO  File: API:Seeking methods in assembly System.Activities, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:02:47,777 INFO  File: ~API:Seeking methods in assembly System.Activities, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:02:47,780 INFO  File: multi-methods-mode=
2016-06-25 23:02:47,803 INFO  File: db.config setting connection-string-regex is empty. Using default: (?:(?<engine>[^|]+?)\|)?(?<conn>[^|]+)
2016-06-25 23:02:47,806 INFO  File: Decrypting connection string dbId=default
2016-06-25 23:02:47,817 INFO  File: Config section 'encrypting' not found. Check web.config!
2016-06-25 23:02:47,822 INFO  File: System.Exception: Error 'Failed to load direct softAES dbAccess encrypting profile.' in method DevReactor.Toolbox.BO.Database.ConnectionInfo+StandardConnectionStringPreparer.decryptPwd ---> System.Exception: Failed to load direct softAES dbAccess encrypting profile. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at DevReactor.Toolbox.BO.Database.ConnectionInfo.StandardConnectionStringPreparer.decryptPwd(String pwdSrc)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
2016-06-25 23:02:47,826 INFO  File: System.Exception: Error 'Object reference not set to an instance of an object.' in method DevReactor.Toolbox.BO.Database.ConnectionInfo+StandardConnectionStringPreparer.decryptPwd ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at DevReactor.Toolbox.BO.Database.ConnectionInfo.StandardConnectionStringPreparer.decryptPwd(String pwdSrc)
   --- End of inner exception stack trace ---
2016-06-25 23:02:47,829 INFO  File: Error decrypting db password. Using password as is.
2016-06-25 23:02:47,834 INFO  File: m_connectionStringsPrepared.Add(Server=MB\SQLEXPRESS;User ID=sa;password=scauser1991;Database=ndr;Persist Security Info=True, Data Source=MB\SQLEXPRESS;Initial Catalog=ndr;Persist Security Info=True;User ID=sa;Password=scauser1991)
2016-06-25 23:02:47,864 INFO  File: toolbox-command-timeout=30
2016-06-25 23:02:47,977 INFO  File: XMLToLowerCase.xslt loaded successfully
2016-06-25 23:02:47,989 INFO  File: 
--Connection Open #4014260 MSSQL|default|Data Source=MB\SQLEXPRESS;Initial Catalog=ndr;Persist Security Info=True;User ID=sa;Password=scauser1991
--Took:  117 ms;
EXEC Account_get	@str_email = N'scauser91@yandex.ua'
,	@str_password = N'123123123'


2016-06-25 23:02:47,998 INFO  File: MemorySessionStorage.Add: 98ec94a3-2826-4314-b91c-192b629e8dfb+7+Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36+127.0.0.1+http://api.research.local+API_WEB+25.06.2016 23:02:47
2016-06-25 23:02:48,278 INFO  File: MemorySessionStorage.GetStrong(91AD152D-5C84-4EEB-9C77-DF394077C0E5, Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36, 127.0.0.1)
2016-06-25 23:02:48,281 INFO  File: MemorySessionStorage.GetStrong(91AD152D-5C84-4EEB-9C77-DF394077C0E5, Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36, 127.0.0.1)=91AD152D-5C84-4EEB-9C77-DF394077C0E5+7+Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36+127.0.0.1+http://api.research.local+API_WEB+25.06.2016 23:02:48
2016-06-25 23:02:48,281 INFO  File: MemorySessionStorage.GetStrong(91AD152D-5C84-4EEB-9C77-DF394077C0E5, Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36, 127.0.0.1)
2016-06-25 23:02:48,287 INFO  File: MemorySessionStorage.GetStrong(91AD152D-5C84-4EEB-9C77-DF394077C0E5, Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36, 127.0.0.1)=91AD152D-5C84-4EEB-9C77-DF394077C0E5+7+Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36+127.0.0.1+http://api.research.local+API_WEB+25.06.2016 23:02:48
2016-06-25 23:02:48,288 INFO  File: 
--Connection Open #9453167 MSSQL|default|Data Source=MB\SQLEXPRESS;Initial Catalog=ndr;Persist Security Info=True;User ID=sa;Password=scauser1991
--Took:  002 ms;
EXEC Account_get	@pk = 7


2016-06-25 23:02:48,292 INFO  File: 
--Connection Open #12036987 MSSQL|default|Data Source=MB\SQLEXPRESS;Initial Catalog=ndr;Persist Security Info=True;User ID=sa;Password=scauser1991
--Took:  001 ms;
EXEC Account_get	@pk = 7


2016-06-25 23:02:48,295 ERROR File: Error 'Failed to load toolbox-baseobject-cache-get-standard settings in db.config. Using default instead.' in method DevReactor.Toolbox.BO.Filter.get_cCacheTimeGetStandard
System.Exception: Failed to load toolbox-baseobject-cache-get-standard settings in db.config. Using default instead. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: String
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at DevReactor.Toolbox.BO.Filter.get_cCacheTimeGetStandard()
   --- End of inner exception stack trace ---
2016-06-25 23:23:47,503 INFO  File: Research.Api ended
2016-06-25 23:34:21,344 INFO  File: Research.Api started
2016-06-25 23:34:21,503 INFO  File: MemorySessionStorage.GetStrong(91AD152D-5C84-4EEB-9C77-DF394077C0E5, Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36, 127.0.0.1)
2016-06-25 23:34:21,506 INFO  File: MemorySessionStorage.GetStrong(91AD152D-5C84-4EEB-9C77-DF394077C0E5, Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36, 127.0.0.1)=
2016-06-25 23:34:21,508 INFO  File: API:Seeking methods in assembly mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:34:21,524 INFO  File: ~API:Seeking methods in assembly mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:34:21,527 INFO  File: API:Seeking methods in assembly System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:34:21,542 INFO  File: ~API:Seeking methods in assembly System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:34:21,544 INFO  File: API:Seeking methods in assembly System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:34:21,556 INFO  File: ~API:Seeking methods in assembly System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:34:21,558 INFO  File: API:Seeking methods in assembly System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:34:21,566 INFO  File: ~API:Seeking methods in assembly System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:34:21,568 INFO  File: API:Seeking methods in assembly System.Web.ApplicationServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:34:21,571 INFO  File: ~API:Seeking methods in assembly System.Web.ApplicationServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:34:21,573 INFO  File: API:Seeking methods in assembly System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:34:21,577 INFO  File: ~API:Seeking methods in assembly System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:34:21,579 INFO  File: API:Seeking methods in assembly System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:34:21,587 INFO  File: ~API:Seeking methods in assembly System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:34:21,590 INFO  File: API:Seeking methods in assembly System.Runtime.Caching, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:34:21,593 INFO  File: ~API:Seeking methods in assembly System.Runtime.Caching, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:34:21,595 INFO  File: API:Seeking methods in assembly Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:34:21,598 INFO  File: ~API:Seeking methods in assembly Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:34:21,600 INFO  File: API:Seeking methods in assembly Microsoft.JScript, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:34:21,604 INFO  File: ~API:Seeking methods in assembly Microsoft.JScript, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:34:21,607 INFO  File: API:Seeking methods in assembly Microsoft.VisualStudio.Web.PageInspector.Loader, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:34:21,609 INFO  File: ~API:Seeking methods in assembly Microsoft.VisualStudio.Web.PageInspector.Loader, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:34:21,611 INFO  File: API:Seeking methods in assembly Microsoft.VisualStudio.Web.PageInspector.Runtime, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:34:21,614 INFO  File: ~API:Seeking methods in assembly Microsoft.VisualStudio.Web.PageInspector.Runtime, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:34:21,617 INFO  File: API:Seeking methods in assembly App_global.asax.66muct9v, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:34:21,619 INFO  File: ~API:Seeking methods in assembly App_global.asax.66muct9v, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:34:21,621 INFO  File: API:Seeking methods in assembly Research.Web.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:34:21,624 INFO  File: API:Method added: Account.Login
2016-06-25 23:34:21,626 INFO  File: API:Method added: Account.Read
2016-06-25 23:34:21,629 INFO  File: API:Method added: Account.Registration
2016-06-25 23:34:21,631 INFO  File: API:Method added: Account.Logout
2016-06-25 23:34:21,633 INFO  File: API:Method added: Account.GetStudents
2016-06-25 23:34:21,635 INFO  File: API:Method added: Account.SetStudent
2016-06-25 23:34:21,637 INFO  File: API:Method added: Questions.Get
2016-06-25 23:34:21,640 INFO  File: API:Method added: Questions.GetTypes
2016-06-25 23:34:21,642 INFO  File: API:Method added: Questions.GetSubjects
2016-06-25 23:34:21,644 INFO  File: API:Method added: Questions.SetSubject
2016-06-25 23:34:21,646 INFO  File: API:Method added: Questions.GetQuestionByType
2016-06-25 23:34:21,648 INFO  File: API:Method added: Questions.GetNextQuestion
2016-06-25 23:34:21,650 INFO  File: API:Method added: Questions.GetAllForQuestions
2016-06-25 23:34:21,652 INFO  File: API:Method added: Questions.SetQuestion
2016-06-25 23:34:21,655 INFO  File: API:Method added: Questions.GetQuestions
2016-06-25 23:34:21,657 INFO  File: ~API:Seeking methods in assembly Research.Web.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:34:21,659 INFO  File: API:Seeking methods in assembly System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:34:21,667 INFO  File: ~API:Seeking methods in assembly System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:34:21,670 INFO  File: API:Seeking methods in assembly log4net, Version=1.2.13.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a
2016-06-25 23:34:21,677 INFO  File: ~API:Seeking methods in assembly log4net, Version=1.2.13.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a
2016-06-25 23:34:21,679 INFO  File: API:Seeking methods in assembly DevReactor.Toolbox.Tools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:34:21,682 INFO  File: ~API:Seeking methods in assembly DevReactor.Toolbox.Tools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:34:21,684 INFO  File: API:Seeking methods in assembly DevReactor.Toolbox.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:34:21,688 INFO  File: ~API:Seeking methods in assembly DevReactor.Toolbox.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:34:21,691 INFO  File: API:Seeking methods in assembly System.Web.Mobile, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:34:21,722 INFO  File: ~API:Seeking methods in assembly System.Web.Mobile, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:34:21,725 INFO  File: API:Seeking methods in assembly System.Web.RegularExpressions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:34:21,728 INFO  File: ~API:Seeking methods in assembly System.Web.RegularExpressions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:34:21,730 INFO  File: API:Seeking methods in assembly Microsoft.VisualStudio.Web.PageInspector.Tracing, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:34:21,733 INFO  File: ~API:Seeking methods in assembly Microsoft.VisualStudio.Web.PageInspector.Tracing, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:34:21,736 INFO  File: API:Seeking methods in assembly App_Web_wnfrcjdk, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:34:21,738 INFO  File: ~API:Seeking methods in assembly App_Web_wnfrcjdk, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:34:21,741 INFO  File: API:Seeking methods in assembly Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
2016-06-25 23:34:21,750 INFO  File: ~API:Seeking methods in assembly Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
2016-06-25 23:34:21,753 INFO  File: API:Seeking methods in assembly System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:34:21,755 INFO  File: ~API:Seeking methods in assembly System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:34:21,757 INFO  File: API:Seeking methods in assembly System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:34:21,762 INFO  File: ~API:Seeking methods in assembly System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:34:21,764 INFO  File: API:Seeking methods in assembly System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:34:21,767 INFO  File: ~API:Seeking methods in assembly System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:34:21,769 INFO  File: API:Seeking methods in assembly System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:34:21,777 INFO  File: ~API:Seeking methods in assembly System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:34:21,797 INFO  File: API:Seeking methods in assembly System.ServiceModel.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:34:21,801 INFO  File: ~API:Seeking methods in assembly System.ServiceModel.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:34:21,804 INFO  File: API:Seeking methods in assembly Research.Logic, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:34:21,807 INFO  File: ~API:Seeking methods in assembly Research.Logic, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:34:21,809 INFO  File: API:Seeking methods in assembly System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:34:21,813 INFO  File: ~API:Seeking methods in assembly System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:34:21,816 INFO  File: API:Seeking methods in assembly DevReactor.Toolbox.BO, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:34:21,820 INFO  File: ~API:Seeking methods in assembly DevReactor.Toolbox.BO, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:34:21,822 INFO  File: API:Seeking methods in assembly System.WorkflowServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:34:21,847 INFO  File: ~API:Seeking methods in assembly System.WorkflowServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:34:21,850 INFO  File: API:Seeking methods in assembly MaxMind.GeoIP2, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:34:21,853 INFO  File: ~API:Seeking methods in assembly MaxMind.GeoIP2, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:34:21,856 INFO  File: API:Seeking methods in assembly System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:34:21,861 INFO  File: ~API:Seeking methods in assembly System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:34:21,864 INFO  File: API:Seeking methods in assembly System.ServiceModel.Activation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:34:21,867 INFO  File: ~API:Seeking methods in assembly System.ServiceModel.Activation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:34:21,870 INFO  File: API:Seeking methods in assembly System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:34:21,891 INFO  File: ~API:Seeking methods in assembly System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:34:21,894 INFO  File: API:Seeking methods in assembly Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:34:21,897 INFO  File: ~API:Seeking methods in assembly Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:34:21,900 INFO  File: API:Seeking methods in assembly System.ServiceModel.Activities, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:34:21,904 INFO  File: ~API:Seeking methods in assembly System.ServiceModel.Activities, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:34:21,906 INFO  File: API:Seeking methods in assembly MaxMind.Db, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:34:21,909 INFO  File: ~API:Seeking methods in assembly MaxMind.Db, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:34:21,911 INFO  File: API:Seeking methods in assembly System.Data.DataSetExtensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:34:21,915 INFO  File: ~API:Seeking methods in assembly System.Data.DataSetExtensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:34:21,918 INFO  File: API:Seeking methods in assembly Oracle.ManagedDataAccess, Version=4.121.1.0, Culture=neutral, PublicKeyToken=89b483f429c47342
2016-06-25 23:34:21,937 INFO  File: ~API:Seeking methods in assembly Oracle.ManagedDataAccess, Version=4.121.1.0, Culture=neutral, PublicKeyToken=89b483f429c47342
2016-06-25 23:34:21,940 INFO  File: API:Seeking methods in assembly System.Web.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:34:21,943 INFO  File: ~API:Seeking methods in assembly System.Web.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:34:21,946 INFO  File: API:Seeking methods in assembly DevReactor.Toolbox.Encrypting, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:34:21,948 INFO  File: ~API:Seeking methods in assembly DevReactor.Toolbox.Encrypting, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:34:21,950 INFO  File: API:Seeking methods in assembly System.Web.DynamicData, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:34:21,958 INFO  File: ~API:Seeking methods in assembly System.Web.DynamicData, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:34:21,961 INFO  File: API:Seeking methods in assembly System.ComponentModel.DataAnnotations, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:34:21,963 INFO  File: ~API:Seeking methods in assembly System.ComponentModel.DataAnnotations, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:34:21,966 INFO  File: API:Seeking methods in assembly RestSharp, Version=105.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:34:21,974 INFO  File: ~API:Seeking methods in assembly RestSharp, Version=105.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:34:21,976 INFO  File: API:Seeking methods in assembly Research.BO, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:34:21,979 INFO  File: ~API:Seeking methods in assembly Research.BO, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:34:21,981 INFO  File: API:Seeking methods in assembly System.EnterpriseServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:34:21,989 INFO  File: ~API:Seeking methods in assembly System.EnterpriseServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:34:21,992 INFO  File: API:Seeking methods in assembly System.Activities, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:34:22,004 INFO  File: ~API:Seeking methods in assembly System.Activities, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:34:22,007 INFO  File: multi-methods-mode=
2016-06-25 23:34:22,011 INFO  File: {
  "Name": "Questions.GetSubjects",
  "Result": {
    "Error": {
      "Code": 0
    }
  }
}
2016-06-25 23:34:23,074 INFO  File: db.config setting connection-string-regex is empty. Using default: (?:(?<engine>[^|]+?)\|)?(?<conn>[^|]+)
2016-06-25 23:34:23,077 INFO  File: Decrypting connection string dbId=default
2016-06-25 23:34:23,086 INFO  File: Config section 'encrypting' not found. Check web.config!
2016-06-25 23:34:23,091 INFO  File: System.Exception: Error 'Failed to load direct softAES dbAccess encrypting profile.' in method DevReactor.Toolbox.BO.Database.ConnectionInfo+StandardConnectionStringPreparer.decryptPwd ---> System.Exception: Failed to load direct softAES dbAccess encrypting profile. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at DevReactor.Toolbox.BO.Database.ConnectionInfo.StandardConnectionStringPreparer.decryptPwd(String pwdSrc)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
2016-06-25 23:34:23,094 INFO  File: System.Exception: Error 'Object reference not set to an instance of an object.' in method DevReactor.Toolbox.BO.Database.ConnectionInfo+StandardConnectionStringPreparer.decryptPwd ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at DevReactor.Toolbox.BO.Database.ConnectionInfo.StandardConnectionStringPreparer.decryptPwd(String pwdSrc)
   --- End of inner exception stack trace ---
2016-06-25 23:34:23,097 INFO  File: Error decrypting db password. Using password as is.
2016-06-25 23:34:23,101 INFO  File: m_connectionStringsPrepared.Add(Server=MB\SQLEXPRESS;User ID=sa;password=scauser1991;Database=ndr;Persist Security Info=True, Data Source=MB\SQLEXPRESS;Initial Catalog=ndr;Persist Security Info=True;User ID=sa;Password=scauser1991)
2016-06-25 23:34:23,113 INFO  File: toolbox-command-timeout=30
2016-06-25 23:34:23,164 INFO  File: XMLToLowerCase.xslt loaded successfully
2016-06-25 23:34:23,172 INFO  File: 
--Connection Open #295723 MSSQL|default|Data Source=MB\SQLEXPRESS;Initial Catalog=ndr;Persist Security Info=True;User ID=sa;Password=scauser1991
--Took:  055 ms;
EXEC Account_get	@str_email = N'scauser91@yandex.ua'
,	@str_password = N'123123123'


2016-06-25 23:34:23,175 INFO  File: MemorySessionStorage.Add: f49169fc-39e6-4aa5-83a6-cb7d93b3588c+7+Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36+127.0.0.1+http://api.research.local+API_WEB+25.06.2016 23:34:23
2016-06-25 23:34:23,215 INFO  File: MemorySessionStorage.GetStrong(16AD08F6-1944-45CD-AD08-E43C98A64E78, Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36, 127.0.0.1)
2016-06-25 23:34:23,218 INFO  File: MemorySessionStorage.GetStrong(16AD08F6-1944-45CD-AD08-E43C98A64E78, Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36, 127.0.0.1)=16AD08F6-1944-45CD-AD08-E43C98A64E78+7+Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36+127.0.0.1+http://api.research.local+API_WEB+25.06.2016 23:34:23
2016-06-25 23:34:23,218 INFO  File: MemorySessionStorage.GetStrong(16AD08F6-1944-45CD-AD08-E43C98A64E78, Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36, 127.0.0.1)
2016-06-25 23:34:23,222 INFO  File: MemorySessionStorage.GetStrong(16AD08F6-1944-45CD-AD08-E43C98A64E78, Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36, 127.0.0.1)=16AD08F6-1944-45CD-AD08-E43C98A64E78+7+Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36+127.0.0.1+http://api.research.local+API_WEB+25.06.2016 23:34:23
2016-06-25 23:34:23,222 INFO  File: 
--Connection Open #10941773 MSSQL|default|Data Source=MB\SQLEXPRESS;Initial Catalog=ndr;Persist Security Info=True;User ID=sa;Password=scauser1991
--Took:  002 ms;
EXEC Account_get	@pk = 7


2016-06-25 23:34:23,227 INFO  File: 
--Connection Open #29385934 MSSQL|default|Data Source=MB\SQLEXPRESS;Initial Catalog=ndr;Persist Security Info=True;User ID=sa;Password=scauser1991
--Took:  001 ms;
EXEC Account_get	@pk = 7


2016-06-25 23:34:23,228 ERROR File: Error 'Failed to load toolbox-baseobject-cache-get-standard settings in db.config. Using default instead.' in method DevReactor.Toolbox.BO.Filter.get_cCacheTimeGetStandard
System.Exception: Failed to load toolbox-baseobject-cache-get-standard settings in db.config. Using default instead. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: String
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at DevReactor.Toolbox.BO.Filter.get_cCacheTimeGetStandard()
   --- End of inner exception stack trace ---
2016-06-25 23:34:24,002 INFO  File: MemorySessionStorage.GetStrong(16AD08F6-1944-45CD-AD08-E43C98A64E78, Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36, 127.0.0.1)
2016-06-25 23:34:24,007 INFO  File: MemorySessionStorage.GetStrong(16AD08F6-1944-45CD-AD08-E43C98A64E78, Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36, 127.0.0.1)=16AD08F6-1944-45CD-AD08-E43C98A64E78+7+Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36+127.0.0.1+http://api.research.local+API_WEB+25.06.2016 23:34:24
2016-06-25 23:34:24,021 INFO  File: 
--Connection Open #34821892 MSSQL|default|Data Source=MB\SQLEXPRESS;Initial Catalog=ndr;Persist Security Info=True;User ID=sa;Password=scauser1991
--Took:  010 ms;
EXEC Theme_get

2016-06-25 23:40:35,683 INFO  File: Research.Api ended
2016-06-25 23:42:21,996 INFO  File: Research.Api started
2016-06-25 23:42:22,350 INFO  File: MemorySessionStorage.GetStrong(16AD08F6-1944-45CD-AD08-E43C98A64E78, Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36, 127.0.0.1)
2016-06-25 23:42:22,353 INFO  File: MemorySessionStorage.GetStrong(16AD08F6-1944-45CD-AD08-E43C98A64E78, Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36, 127.0.0.1)=
2016-06-25 23:42:22,353 INFO  File: MemorySessionStorage.GetStrong(16AD08F6-1944-45CD-AD08-E43C98A64E78, Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36, 127.0.0.1)
2016-06-25 23:42:22,358 INFO  File: MemorySessionStorage.GetStrong(16AD08F6-1944-45CD-AD08-E43C98A64E78, Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36, 127.0.0.1)=
2016-06-25 23:42:22,358 INFO  File: MemorySessionStorage.GetStrong(16AD08F6-1944-45CD-AD08-E43C98A64E78, Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36, 127.0.0.1)
2016-06-25 23:42:22,360 INFO  File: API:Seeking methods in assembly mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:42:22,362 INFO  File: MemorySessionStorage.GetStrong(16AD08F6-1944-45CD-AD08-E43C98A64E78, Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36, 127.0.0.1)=
2016-06-25 23:42:22,377 INFO  File: ~API:Seeking methods in assembly mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:42:22,380 INFO  File: API:Seeking methods in assembly System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:42:22,395 INFO  File: ~API:Seeking methods in assembly System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:42:22,398 INFO  File: API:Seeking methods in assembly System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:42:22,409 INFO  File: ~API:Seeking methods in assembly System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:42:22,412 INFO  File: API:Seeking methods in assembly System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:42:22,418 INFO  File: ~API:Seeking methods in assembly System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:42:22,421 INFO  File: API:Seeking methods in assembly System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:42:22,424 INFO  File: ~API:Seeking methods in assembly System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:42:22,427 INFO  File: API:Seeking methods in assembly System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:42:22,433 INFO  File: ~API:Seeking methods in assembly System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:42:22,437 INFO  File: API:Seeking methods in assembly System.Data.SqlXml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:42:22,441 INFO  File: ~API:Seeking methods in assembly System.Data.SqlXml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:42:22,444 INFO  File: API:Seeking methods in assembly System.Web.ApplicationServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:42:22,446 INFO  File: ~API:Seeking methods in assembly System.Web.ApplicationServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:42:22,449 INFO  File: API:Seeking methods in assembly System.Runtime.Caching, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:42:22,451 INFO  File: ~API:Seeking methods in assembly System.Runtime.Caching, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:42:22,453 INFO  File: API:Seeking methods in assembly Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:42:22,456 INFO  File: ~API:Seeking methods in assembly Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:42:22,458 INFO  File: API:Seeking methods in assembly System.Web.RegularExpressions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:42:22,461 INFO  File: ~API:Seeking methods in assembly System.Web.RegularExpressions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:42:22,463 INFO  File: API:Seeking methods in assembly Microsoft.JScript, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:42:22,467 INFO  File: ~API:Seeking methods in assembly Microsoft.JScript, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:42:22,470 INFO  File: API:Seeking methods in assembly Microsoft.VisualStudio.Web.PageInspector.Loader, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:42:22,473 INFO  File: ~API:Seeking methods in assembly Microsoft.VisualStudio.Web.PageInspector.Loader, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:42:22,475 INFO  File: API:Seeking methods in assembly Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:42:22,478 INFO  File: ~API:Seeking methods in assembly Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:42:22,480 INFO  File: API:Seeking methods in assembly System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:42:22,486 INFO  File: ~API:Seeking methods in assembly System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:42:22,488 INFO  File: API:Seeking methods in assembly System.Web.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:42:22,492 INFO  File: ~API:Seeking methods in assembly System.Web.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:42:22,494 INFO  File: API:Seeking methods in assembly System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:42:22,497 INFO  File: ~API:Seeking methods in assembly System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:42:22,500 INFO  File: API:Seeking methods in assembly System.EnterpriseServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:42:22,505 INFO  File: ~API:Seeking methods in assembly System.EnterpriseServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:42:22,508 INFO  File: API:Seeking methods in assembly System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:42:22,512 INFO  File: ~API:Seeking methods in assembly System.IdentityModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:42:22,514 INFO  File: API:Seeking methods in assembly System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:42:22,518 INFO  File: ~API:Seeking methods in assembly System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:42:22,520 INFO  File: API:Seeking methods in assembly System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:42:22,538 INFO  File: ~API:Seeking methods in assembly System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:42:22,541 INFO  File: API:Seeking methods in assembly System.ServiceModel.Activation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:42:22,544 INFO  File: ~API:Seeking methods in assembly System.ServiceModel.Activation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:42:22,547 INFO  File: API:Seeking methods in assembly System.ServiceModel.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:42:22,550 INFO  File: ~API:Seeking methods in assembly System.ServiceModel.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:42:22,552 INFO  File: API:Seeking methods in assembly System.Activities, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:42:22,558 INFO  File: ~API:Seeking methods in assembly System.Activities, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:42:22,561 INFO  File: API:Seeking methods in assembly System.ServiceModel.Activities, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:42:22,564 INFO  File: ~API:Seeking methods in assembly System.ServiceModel.Activities, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:42:22,566 INFO  File: API:Seeking methods in assembly System.WorkflowServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:42:22,572 INFO  File: ~API:Seeking methods in assembly System.WorkflowServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:42:22,575 INFO  File: API:Seeking methods in assembly System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:42:22,578 INFO  File: ~API:Seeking methods in assembly System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:42:22,581 INFO  File: API:Seeking methods in assembly System.Data.DataSetExtensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:42:22,583 INFO  File: ~API:Seeking methods in assembly System.Data.DataSetExtensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:42:22,585 INFO  File: API:Seeking methods in assembly System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:42:22,587 INFO  File: ~API:Seeking methods in assembly System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:42:22,590 INFO  File: API:Seeking methods in assembly System.ComponentModel.DataAnnotations, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:42:22,593 INFO  File: ~API:Seeking methods in assembly System.ComponentModel.DataAnnotations, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:42:22,595 INFO  File: API:Seeking methods in assembly System.Web.DynamicData, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:42:22,598 INFO  File: ~API:Seeking methods in assembly System.Web.DynamicData, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2016-06-25 23:42:22,600 INFO  File: API:Seeking methods in assembly DevReactor.Toolbox.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:42:22,604 INFO  File: ~API:Seeking methods in assembly DevReactor.Toolbox.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:42:22,606 INFO  File: API:Seeking methods in assembly DevReactor.Toolbox.BO, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:42:22,610 INFO  File: ~API:Seeking methods in assembly DevReactor.Toolbox.BO, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:42:22,612 INFO  File: API:Seeking methods in assembly DevReactor.Toolbox.Encrypting, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:42:22,614 INFO  File: ~API:Seeking methods in assembly DevReactor.Toolbox.Encrypting, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:42:22,616 INFO  File: API:Seeking methods in assembly DevReactor.Toolbox.Tools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:42:22,619 INFO  File: ~API:Seeking methods in assembly DevReactor.Toolbox.Tools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:42:22,622 INFO  File: API:Seeking methods in assembly log4net, Version=1.2.13.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a
2016-06-25 23:42:22,629 INFO  File: ~API:Seeking methods in assembly log4net, Version=1.2.13.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a
2016-06-25 23:42:22,632 INFO  File: API:Seeking methods in assembly MaxMind.Db, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:42:22,634 INFO  File: ~API:Seeking methods in assembly MaxMind.Db, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:42:22,636 INFO  File: API:Seeking methods in assembly MaxMind.GeoIP2, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:42:22,639 INFO  File: ~API:Seeking methods in assembly MaxMind.GeoIP2, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:42:22,641 INFO  File: API:Seeking methods in assembly Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
2016-06-25 23:42:22,650 INFO  File: ~API:Seeking methods in assembly Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
2016-06-25 23:42:22,652 INFO  File: API:Seeking methods in assembly Oracle.ManagedDataAccess, Version=4.121.1.0, Culture=neutral, PublicKeyToken=89b483f429c47342
2016-06-25 23:42:22,671 INFO  File: ~API:Seeking methods in assembly Oracle.ManagedDataAccess, Version=4.121.1.0, Culture=neutral, PublicKeyToken=89b483f429c47342
2016-06-25 23:42:22,674 INFO  File: API:Seeking methods in assembly Research.BO, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:42:22,677 INFO  File: ~API:Seeking methods in assembly Research.BO, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:42:22,680 INFO  File: API:Seeking methods in assembly Research.Logic, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:42:22,682 INFO  File: ~API:Seeking methods in assembly Research.Logic, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:42:22,684 INFO  File: API:Seeking methods in assembly Research.Web.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:42:22,686 INFO  File: API:Method added: Account.Login
2016-06-25 23:42:22,689 INFO  File: API:Method added: Account.Read
2016-06-25 23:42:22,691 INFO  File: API:Method added: Account.Registration
2016-06-25 23:42:22,693 INFO  File: API:Method added: Account.Logout
2016-06-25 23:42:22,696 INFO  File: API:Method added: Account.GetStudents
2016-06-25 23:42:22,698 INFO  File: API:Method added: Account.SetStudent
2016-06-25 23:42:22,700 INFO  File: API:Method added: Questions.Get
2016-06-25 23:42:22,702 INFO  File: API:Method added: Questions.GetTypes
2016-06-25 23:42:22,704 INFO  File: API:Method added: Questions.GetSubjects
2016-06-25 23:42:22,706 INFO  File: API:Method added: Questions.SetSubject
2016-06-25 23:42:22,709 INFO  File: API:Method added: Questions.GetQuestionByType
2016-06-25 23:42:22,711 INFO  File: API:Method added: Questions.GetNextQuestion
2016-06-25 23:42:22,713 INFO  File: API:Method added: Questions.GetAllForQuestions
2016-06-25 23:42:22,715 INFO  File: API:Method added: Questions.SetQuestion
2016-06-25 23:42:22,717 INFO  File: API:Method added: Questions.GetQuestions
2016-06-25 23:42:22,719 INFO  File: ~API:Seeking methods in assembly Research.Web.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:42:22,722 INFO  File: API:Seeking methods in assembly RestSharp, Version=105.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:42:22,730 INFO  File: ~API:Seeking methods in assembly RestSharp, Version=105.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:42:22,732 INFO  File: API:Seeking methods in assembly System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:42:22,738 INFO  File: ~API:Seeking methods in assembly System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:42:22,741 INFO  File: API:Seeking methods in assembly Microsoft.VisualStudio.Web.PageInspector.Runtime, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:42:22,743 INFO  File: ~API:Seeking methods in assembly Microsoft.VisualStudio.Web.PageInspector.Runtime, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:42:22,745 INFO  File: API:Seeking methods in assembly Microsoft.VisualStudio.Web.PageInspector.Tracing, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:42:22,747 INFO  File: ~API:Seeking methods in assembly Microsoft.VisualStudio.Web.PageInspector.Tracing, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:42:22,750 INFO  File: API:Seeking methods in assembly System.Data.Services.Design, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:42:22,762 INFO  File: ~API:Seeking methods in assembly System.Data.Services.Design, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:42:22,765 INFO  File: API:Seeking methods in assembly App_global.asax.ccvmq7sg, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:42:22,767 INFO  File: ~API:Seeking methods in assembly App_global.asax.ccvmq7sg, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:42:22,769 INFO  File: API:Seeking methods in assembly System.Web.Mobile, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:42:22,776 INFO  File: ~API:Seeking methods in assembly System.Web.Mobile, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
2016-06-25 23:42:22,779 INFO  File: API:Seeking methods in assembly App_Web_arym0i4m, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:42:22,781 INFO  File: ~API:Seeking methods in assembly App_Web_arym0i4m, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
2016-06-25 23:42:22,783 INFO  File: API:Seeking methods in assembly System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:42:22,785 INFO  File: ~API:Seeking methods in assembly System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:42:22,787 INFO  File: API:Seeking methods in assembly System.Transactions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:42:22,791 INFO  File: ~API:Seeking methods in assembly System.Transactions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
2016-06-25 23:42:22,794 INFO  File: multi-methods-mode=
2016-06-25 23:42:22,794 INFO  File: multi-methods-mode=
2016-06-25 23:42:22,794 INFO  File: multi-methods-mode=
2016-06-25 23:42:22,801 INFO  File: {
  "Name": "Questions.GetSubjects",
  "Result": {
    "Error": {
      "Code": 0
    }
  }
}
2016-06-25 23:42:22,801 INFO  File: {
  "Name": "Account.Read",
  "Result": {
    "Error": {
      "Code": 0
    }
  }
}
2016-06-25 23:42:22,801 INFO  File: {
  "Name": "Account.Read",
  "Result": {
    "Error": {
      "Code": 0
    }
  }
}
2016-06-25 23:42:29,292 INFO  File: db.config setting connection-string-regex is empty. Using default: (?:(?<engine>[^|]+?)\|)?(?<conn>[^|]+)
2016-06-25 23:42:29,297 INFO  File: Decrypting connection string dbId=default
2016-06-25 23:42:29,306 INFO  File: Config section 'encrypting' not found. Check web.config!
2016-06-25 23:42:29,310 INFO  File: System.Exception: Error 'Failed to load direct softAES dbAccess encrypting profile.' in method DevReactor.Toolbox.BO.Database.ConnectionInfo+StandardConnectionStringPreparer.decryptPwd ---> System.Exception: Failed to load direct softAES dbAccess encrypting profile. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at DevReactor.Toolbox.BO.Database.ConnectionInfo.StandardConnectionStringPreparer.decryptPwd(String pwdSrc)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
2016-06-25 23:42:29,314 INFO  File: System.Exception: Error 'Object reference not set to an instance of an object.' in method DevReactor.Toolbox.BO.Database.ConnectionInfo+StandardConnectionStringPreparer.decryptPwd ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at DevReactor.Toolbox.BO.Database.ConnectionInfo.StandardConnectionStringPreparer.decryptPwd(String pwdSrc)
   --- End of inner exception stack trace ---
2016-06-25 23:42:29,316 INFO  File: Error decrypting db password. Using password as is.
2016-06-25 23:42:29,319 INFO  File: m_connectionStringsPrepared.Add(Server=MB\SQLEXPRESS;User ID=sa;password=scauser1991;Database=ndr;Persist Security Info=True, Data Source=MB\SQLEXPRESS;Initial Catalog=ndr;Persist Security Info=True;User ID=sa;Password=scauser1991)
2016-06-25 23:42:29,327 INFO  File: toolbox-command-timeout=30
2016-06-25 23:42:29,345 INFO  File: XMLToLowerCase.xslt loaded successfully
2016-06-25 23:42:29,356 INFO  File: 
--Connection Open #42670487 MSSQL|default|Data Source=MB\SQLEXPRESS;Initial Catalog=ndr;Persist Security Info=True;User ID=sa;Password=scauser1991
--Took:  020 ms;
EXEC Account_get	@str_email = N'scauser91@yandex.ua'
,	@str_password = N'123123123'


2016-06-25 23:42:29,366 INFO  File: MemorySessionStorage.Add: ae71c5d1-3fca-47fb-9e8c-d78ae8c58025+7+Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36+127.0.0.1+http://api.research.local+API_WEB+25.06.2016 23:42:29
2016-06-25 23:42:29,400 INFO  File: MemorySessionStorage.GetStrong(C6E5F8F0-FE76-47A4-9D44-819F15B51FF6, Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36, 127.0.0.1)
2016-06-25 23:42:29,404 INFO  File: MemorySessionStorage.GetStrong(C6E5F8F0-FE76-47A4-9D44-819F15B51FF6, Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36, 127.0.0.1)=C6E5F8F0-FE76-47A4-9D44-819F15B51FF6+7+Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36+127.0.0.1+http://api.research.local+API_WEB+25.06.2016 23:42:29
2016-06-25 23:42:29,404 INFO  File: MemorySessionStorage.GetStrong(C6E5F8F0-FE76-47A4-9D44-819F15B51FF6, Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36, 127.0.0.1)
2016-06-25 23:42:29,409 INFO  File: MemorySessionStorage.GetStrong(C6E5F8F0-FE76-47A4-9D44-819F15B51FF6, Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36, 127.0.0.1)=C6E5F8F0-FE76-47A4-9D44-819F15B51FF6+7+Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36+127.0.0.1+http://api.research.local+API_WEB+25.06.2016 23:42:29
2016-06-25 23:42:29,410 INFO  File: 
--Connection Open #46427390 MSSQL|default|Data Source=MB\SQLEXPRESS;Initial Catalog=ndr;Persist Security Info=True;User ID=sa;Password=scauser1991
--Took:  001 ms;
EXEC Account_get	@pk = 7


2016-06-25 23:42:29,416 INFO  File: 
--Connection Open #35613425 MSSQL|default|Data Source=MB\SQLEXPRESS;Initial Catalog=ndr;Persist Security Info=True;User ID=sa;Password=scauser1991
--Took:  001 ms;
EXEC Account_get	@pk = 7


2016-06-25 23:42:29,418 ERROR File: Error 'Failed to load toolbox-baseobject-cache-get-standard settings in db.config. Using default instead.' in method DevReactor.Toolbox.BO.Filter.get_cCacheTimeGetStandard
System.Exception: Failed to load toolbox-baseobject-cache-get-standard settings in db.config. Using default instead. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: String
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at DevReactor.Toolbox.BO.Filter.get_cCacheTimeGetStandard()
   --- End of inner exception stack trace ---
2016-06-25 23:42:31,196 INFO  File: MemorySessionStorage.GetStrong(C6E5F8F0-FE76-47A4-9D44-819F15B51FF6, Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36, 127.0.0.1)
2016-06-25 23:42:31,202 INFO  File: MemorySessionStorage.GetStrong(C6E5F8F0-FE76-47A4-9D44-819F15B51FF6, Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36, 127.0.0.1)=C6E5F8F0-FE76-47A4-9D44-819F15B51FF6+7+Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36+127.0.0.1+http://api.research.local+API_WEB+25.06.2016 23:42:31
2016-06-25 23:42:31,215 INFO  File: 
--Connection Open #38601272 MSSQL|default|Data Source=MB\SQLEXPRESS;Initial Catalog=ndr;Persist Security Info=True;User ID=sa;Password=scauser1991
--Took:  007 ms;
EXEC Theme_get

2016-06-25 23:42:34,191 INFO  File: MemorySessionStorage.GetStrong(C6E5F8F0-FE76-47A4-9D44-819F15B51FF6, Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36, 127.0.0.1)
2016-06-25 23:42:34,195 INFO  File: MemorySessionStorage.GetStrong(C6E5F8F0-FE76-47A4-9D44-819F15B51FF6, Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36, 127.0.0.1)=C6E5F8F0-FE76-47A4-9D44-819F15B51FF6+7+Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36+127.0.0.1+http://api.research.local+API_WEB+25.06.2016 23:42:34
2016-06-25 23:42:34,219 INFO  File: 
--Connection Open #63295566 MSSQL|default|Data Source=MB\SQLEXPRESS;Initial Catalog=ndr;Persist Security Info=True;User ID=sa;Password=scauser1991
--Took:  014 ms;
EXEC Question_get	@fk_theme = 5
,	@pagesize = 3
,	@page = 1


2016-06-25 23:42:34,233 INFO  File: 
--Connection Open #23606262 MSSQL|default|Data Source=MB\SQLEXPRESS;Initial Catalog=ndr;Persist Security Info=True;User ID=sa;Password=scauser1991
--Took:  010 ms;
EXEC Answer_get	@fk_question = 102


2016-06-25 23:42:34,237 INFO  File: 
--Connection Open #10469283 MSSQL|default|Data Source=MB\SQLEXPRESS;Initial Catalog=ndr;Persist Security Info=True;User ID=sa;Password=scauser1991
--Took:  001 ms;
EXEC Answer_get	@fk_question = 103


2016-06-25 23:42:34,241 INFO  File: 
--Connection Open #16946562 MSSQL|default|Data Source=MB\SQLEXPRESS;Initial Catalog=ndr;Persist Security Info=True;User ID=sa;Password=scauser1991
--Took:  002 ms;
EXEC Answer_get	@fk_question = 104


